spring:
  profiles:
    active: dev

---
spring:
  profiles: dev
a: hh
eureka: 
  client: 
    service-url: 
      defaultZone: http://eureka-dev.com:7001/eureka/   
---
spring:
  profiles: test
eureka: 
  client: 
    service-url: 
      defaultZone: http://eureka-test.com:7001/eureka/
 
