spring:
  profiles:
    active: dev
a: 1
---
server: 
  port: 8201xx
spring:
  profiles: dev
  application: 
    name: microservicecloud-config-dddd
eureka: 
  client: 
    service-url: 
      defaultZone: http://eureka-dev.com:7001/eureka/   
---
server: 
  port: 8202 
spring:
  profiles: test
  application: 
    name: microservicecloud-config-client
eureka: 
  client: 
    service-url: 
      defaultZone: http://eureka-test.com:7001/eureka/
 
